services:
  db:
    image: postgres:16-alpine
    container_name: crypto_exchange_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_exchange_postgres
    ports:
      - "5555:5432"
    volumes:
      - crypto_exchange_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crypto_exchange_postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  crypto_exchange_pgdata: